# Simulation Setup
dt = 0.1 # seconds, time step of simulation
dx = 0.01 # meters, discretisation of cell in 1D

# Cell parameters
Thickness = 0.1 # meters, thickness of cell to simulate; thickness = 2*L
Specific_heat = 1000 # J/(kg*K), specific heat of cell
Conductivity = 0.5 # W/(m*K), through-plane conductivity of cell

# Heat parameters
Temperature_initial = 20 # Deg C, uniform starting temperature of cell and boundaries
Heat_gen = 0 # Watts/m, uniform heat generation by cell
Temperature_side_minusL = 25 # Deg C, temperature applied at x = -L 
Temperature_side_plusL = 25 # Deg C, temperature applied at x = L

