# Simulation Setup
dt = 2                                  # seconds, time step of simulation
total_time = 100000                     # seconds, total time simulated (choose large value for steady state simulation; make sure dT/dt is very small)
dx = 0.2                               # mm, discretisation of cell in 1D
dx_thermal_interface = 0.1                        # mm, discretisation of thermal interface in 1D, use smaller value than cell dx for more precision

# Cell parameters
Thickness = 20                          # mm, thickness of cell to model; thickness = 2*L
Specific_heat = 1000                    # J/(kg*K), specific heat of cell
Conductivity = 0.5                      # W/(m*K), through-plane thermal conductivity of cell
Density = 30                            # kg/m^3, weight density; used to calculate diffusivity (diffusivity = conductivity/(density*specificheat))

# Sensor parameters (and thermal interface material)
Thermal_Interface_Thickness = 2       # mm, thickness of thermal interface material to model
Thermal_Interface_Conductivity = 1.4    # W/(m*K), conductivity of heat flux sensor and thermal interface material

# Heat parameters
Temperature_initial = 25                # Deg C, uniform starting temperature of cell and boundaries
Heat_flux_left = -20                    # Watts/(m^2), heat in from peltier at x = -L surface
Heat_flux_right = 25                    # Watts/(m^2), heat in from peltier at x = L surface
Total_heat_gen = 15                     # Watts/(m^2), total internal heat generation (per area because of 1D model), will be equally distributed in the model 
Heat_loss_heat_transfer_coefficient = 5 # Watts/(m^2*K), total heat loss in system (per area because of 1D model), will be equally distributed in the model (should be negative)
Temperature_ambient = 25                # Deg C, used for calculating heat loss
