# Simulation Setup
dt = 0.01                              # seconds, time step of simulation; if overflow error is occurring, use smaller dt
total_time = 1000                       # seconds, total time simulated (choose large value for steady state simulation; make sure final dT/dt is very small)
n = 200                                 # number of discretised points in 1D, choose around 200 or more for convergence

# Cell parameters
Thickness = 0.01                        # m, thickness of cell to model; thickness = 2*L
Specific_heat = 1000                    # J/(kg*K), specific heat of cell
Conductivity = 0.5                      # W/(m*K), through-plane thermal conductivity of cell
Density = 2000                          # kg/m^3, weight density; used to calculate diffusivity (diffusivity = conductivity/(density*specificheat))

# Sensor parameters (and thermal interface material)
Thermal_Interface_Thickness = 0.0005    # m, thickness of thermal interface material to model
Thermal_Interface_Specific_heat = 100   # J/(kg*K), not used for steady state calculations
Thermal_Interface_Conductivity = 1.2    # W/(m*K), conductivity of heat flux sensor and thermal interface material
Thermal_Interface_Density = 1790        # kg/m^3, , not used for steady state calculations

# Heat parameters
Temperature_initial = 25                # Deg C, uniform starting temperature of cell and boundaries
Temperature_left = 18                   # Watts/(m^2), heat in from peltier at x = -L surface
Temperature_right = 30                  # Watts/(m^2), heat in from peltier at x = L surface
Total_heat_gen = 200                    # Watts/(m^2), total internal heat generation (per area because of 1D model), will be equally distributed in the model 
Heat_loss_heat_transfer_coefficient = 2 # Watts/(m^2*K), total heat loss in system (per area because of 1D model), will be equally distributed in the model (should be negative)
Temperature_ambient = 25                # Deg C, used for calculating heat loss
